### ISSUE TITLE
Needs README.md

### ISSUE THREAD

**Issue by lukie-luke** [codingthunder/JC-Physics-Engine-2D#2]
Consider moving the readme file to the root folder.

**Comment by codingthunder** [comment]
Hi, thanks for the feedback. I'm planning to make a README.md for the root folder as well. I just haven't had a chance to do so yet.  Thanks again for the advice.

**Comment by codingthunder** [comment]
@lukie-luke Thanks again for the feedback. I've made a separate readme for the root folder. Now that's done, I'm going to close this issue.
